services:
#  zipkin-server:
#    image: openzipkin/zipkin:3.5.1
#    container_name: zipkin-server
#    ports:
#      - "9411:9411"
#    restart: always
#    networks:
#      - vandre-network
#
#  naming-server:
#    image: vandre856/naming-service:0.0.1-SNAPSHOT
#    container_name: naming-server
#    ports:
#      - "8761:8761"
#    restart: always
#    depends_on:
#      - zipkin-server
#    environment:
#      SPRING_ZIPKIN_BASEURL: http://zipkin-server:9411
#    networks:
#      - vandre-network
#
#  api-gateway:
#    image: vandre856/api-gateway:0.0.1-SNAPSHOT
#    container_name: api-gateway
#    ports:
#      - "8765:8765"
#    restart: always
#    depends_on:
#      - zipkin-server
#      - naming-server
#    environment:
#      SPRING_ZIPKIN_BASEURL: http://zipkin-server:9411
#      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://naming-server:8761/eureka
#    networks:
#      - vandre-network

#  book-db:
#    image: mysql:9.3.0
#    container_name: book-db
#    ports:
#      - "3310:3306"
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: 123
#      MYSQL_DATABASE: book_service
#      MYSQL_USER: admin
#      MYSQL_PASSWORD: 123
#      TZ: America/Sao_Paulo
#    networks:
#      - vandre-network
#
#  exchange-db:
#    image: mysql:9.3.0
#    container_name: exchange-db
#    ports:
#      - "3308:3306"
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: 123
#      MYSQL_DATABASE: exchange_service
#      MYSQL_USER: admin
#      MYSQL_PASSWORD: 123
#      TZ: America/Sao_Paulo
#    networks:
#      - vandre-network

  exchange-service:
    image: vandre856/exchange-service
    container_name: exchange-service
    restart: always
    build:
      context: ./exchange-service
      dockerfile: Dockerfile
#    depends_on:
#      - zipkin-server
#      - naming-server
#      - exchange-db
    environment:
      TZ: America/Sao_Paulo
#      SPRING_ZIPKIN_BASEURL: http://zipkin-server:9411
#      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://naming-server:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/exchange_service?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123
    ports:
      - "8000:8000"
    networks:
      - vandre-network

  book-service:
    image: vandre856/book-service
    container_name: book-service
    restart: always
    build:
      context: ./book-service
      dockerfile: Dockerfile
#    depends_on:
#      - zipkin-server
#      - naming-server
#      - book-db
    environment:
      TZ: America/Sao_Paulo
#      SPRING_ZIPKIN_BASEURL: http://zipkin-server:9411
#      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://naming-server:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/book_service?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123
    ports:
      - "8100:8100"
    networks:
      - vandre-network

networks:
  vandre-network:
    name: vandre-network
    driver: bridge